### ISSUE TITLE
Add method to extract css and js

### ISSUE THREAD

**Issue by AndreBaumeier** [mmucklo/krumo#22]
currently there's no way to extract the output from Krumo::_css() since it's private. If I want to save the krumo output into multiple log files, I run into the problem that I am not able to even unset the setting beeing used internally (boolean $_css) to determine wether the css/js output should be attached or not.

**Comment by scottchiefbaker** [comment]
@AndreBaumeier is this still an issue we need to look at. I'm going through old bugs today.

**Comment by scottchiefbaker** [comment]
@AndreBaumeier It's been two years and I haven't heard anything on this issue. Closing for now, but willing to re-open if it's still an issue.
