### ISSUE TITLE
Enhancement Request: align keys

### ISSUE THREAD

**Issue by STaRDoGG** [mmucklo/krumo#25]
![2015-04-28_15-35-03](https://cloud.githubusercontent.com/assets/1524526/7379805/04a04cdc-edbd-11e4-8781-7e67a0b4237b.jpg)

I'd like to see the keys in arrays visibly lined up to their parent element, so they are more comfortably viewable.

In the screenshot above for example, the items in the yellow (1) box would be visibly lined evenly up (which they currently already are), and the items in the red (2) boxes would be visibly lined up (which they currently are not).

The lining up would be to find the longest key length of the items in that array, and then `str_pad($key, X, " ", STR_PAD_RIGHT);` the other items within that array so they're all of equal length. This would make the rest of the stuff after it (i.e. the "String(4) => "some value here") appear lined up, essentially Left Justifying everything starting with the Type.

Hopefully I was able to convey what I meant well enough, lol.

Also, I've manually done it to my own krumo class, but it'd be nice if it was done to this repo version as well, so I (and possibly others) don't have to manually do it each update; I have changed all `<strong>` and `<em>` tags in the class to `<span>` classes. I prefer to use the CSS to do all of my styling. =)

**Comment by scottchiefbaker** [comment]
I would support this if it's done correctly. If you've already done it to your repo can you post that code?

**Comment by STaRDoGG** [comment]
Scott:

Glad to hear. =)

No, I haven't don't that to mine, or have my own repo of it. I just downloaded it late last night and have been styling it to my own liking. Other than that I've done no coding on it. I thought I'd come here and post the request instead of doing it myself, since you guys are more intimately knowledgeable of how you've done it's coding, it would probably be less "hacky" then.

**Comment by scottchiefbaker** [comment]
> Also, I've manually done it to my own krumo class, but it'd be nice if it was done to this repo version as well

Sorry I misunderstood. One thing Krumo could use is some CSS clean ups. I'd be curious to see what you've come up with.

**Comment by STaRDoGG** [comment]
I'll be happy to send my style to ya once I finish it, for you to include (or not) if you choose. It would probably be a bit easier for me to maybe email it to you instead of creating my own full repo of Krumo just for the style sheet.

**Comment by STaRDoGG** [comment]
Well, I messed around with it a bit and whipped up a little bit of code. Here's where I left off (ignore the ugly theme, it's not done. Got sidetracked with this alignment code):

![2015-04-29_21-06-47](https://cloud.githubusercontent.com/assets/1524526/7405134/fc691b78-eeb3-11e4-9bf9-c9813be7fc02.jpg)

Where you see the dashes on the right side of some keys is where I left off wrestling with the code. Putting " " (a plain space) as the padding, ends up showing a little info icon saying it contains spaces, along with the spacebar looking icon/text in place of the blank spaces, which is no good for this. If I try to use the html entity ```"&160;"``` it'll add those characters to the key instead of a blank space, which is also no good. Using ```chr(13)``` does the same as the former. So not sure about how to do this as of right now.

It's possible that adding spaces to the keys themselves might not be the best way to do this; maybe adding padding to the Type that comes after it would be better, but that's a whole different barrel of monkeys.

Here's the code I have so far, which is also possibly not the 'best way' of accomplishing this, as opposed to possibly some built-in PHP array functions instead.

Inserted between in ```private static function _array()```:

```
        } else {
            $sort = 0;
        }
```

and

```
        $childCount = count($data);
```


```
				/* Padding Begin ----------------------------------------------------- */

				/* Holds the highest key length per array loop*/
				$intHighest = 0;
				/* Create a new temp array */
				$new = array();

				/* Loop the array, checking the length of each key */
				foreach($data as $key => $value) {

					/* If this key is the longest one so far, add it's length as the highest */
					if (strlen($key) > $intHighest) {$intHighest = strlen($key);}
				}

				/* Now loop it again, padding the shorter keys to match the longest key */
				foreach($data as $key => $value) {


					$key = str_pad($key, $intHighest, "-", STR_PAD_RIGHT);
					$new[$key] = $value;
				}

				/* Save the newly padded array back as the main array */
				$data = $new;

				/* Padding End ------------------------------------------------------- */
```

**Comment by scottchiefbaker** [comment]
I thought about this some more, and it only works if you use a monospace font for your keys. The default (and most) CSS theme uses variable width fonts, which make this less feasible :(

**Comment by STaRDoGG** [comment]
You're right, I used Source Code Pro as my Krumo font. I add this to my style.css:

```@import url(http://fonts.googleapis.com/css?family=Source+Code+Pro:500);```

I suppose it could be added in the Krumo config as an option, with a note mentioning 'if using a monospace font the keys will show as justified'?

**Comment by STaRDoGG** [comment]
I just added this to the krumo.ini:

```
[align]
; If you use a monospace font in your Krumo CSS, this will justify the arrays (Default: false)
align_arrays = true
```

And this to the code:

```
$config_align = Krumo::_config('align','align_arrays', false);

if ($config_align) {
    ...
}
```

**Comment by mmucklo** [comment]
This is an old thread, but reading this it seems that the best way to do this would be to bit the bullet and use html tables here, I could be wrong...

**Comment by scottchiefbaker** [comment]
Reworking the whole thing in tables would be pretty complex. It may be "cheating" but doing it with a monospace font isn't a bad way to go.
