### ISSUE TITLE
Escape <!-- and I suppose -->

### ISSUE THREAD

**Issue by dmyers2004** [mmucklo/krumo#26]
My debug output contains <!-- and Krumo doesn't escape this therefore everything after it is a HTML comment. See excerpt below.

```
...onMouseOver="krumo.over(this);" onMouseOut="krumo.out(this);">
<a class="krumo-name"><!--</a> <em class="krumo-type">String(<strong class="krumo-string-length">7</strong>)</em>  =&gt;  <strong class="krumo-string">&amp;lt;!--</strong></div></li><li class="kru...
```

**Comment by scottchiefbaker** [comment]
You bring up a good point. Should we `htmlentities()` the entire output? I don't think I've ever krumo'd HTML strings before.

**Comment by mmucklo** [comment]
Might not be a bad idea...(htmlentities)



On May 4, 2015, at 10:32 AM, Scott Baker <notifications@github.com> wrote:

You bring up a good point. Should we htmlentities() the entire output? I
don't think I've ever krumo'd HTML strings before.

—
Reply to this email directly or view it on GitHub
<https://github.com/oodle/krumo/issues/26#issuecomment-98787797>.

**Comment by scottchiefbaker** [comment]
I'm really surprised we haven't run in to this before. I'll have to do some investigation. Should be an easy fix though.

**Comment by scottchiefbaker** [comment]
Sorry it too me so long to look at this. I'm not seeing the problem you're seeing. If I look at the code we're already escaping string output:

https://github.com/oodle/krumo/blob/master/class.krumo.php#L1452

Are you sure you're running the latest version?

**Comment by scottchiefbaker** [comment]
@dmyers2004 any update on this issue?

**Comment by scottchiefbaker** [comment]
Closing this issue because it's been more than 2 years. Will to re-open if it's still an issue.
