### ISSUE TITLE
krumo provide more info on a array-casted object than on the object itself

### ISSUE THREAD

**Issue by grippon** [mmucklo/krumo#29]
I have a code with differents Exceptions being inherited from Exception.  
When i krumo an exception, i'm sad because there is not the trace.  
But if i cast the exception in an array, i see the trace. (I did that because the old krumo didn't work on objects)  

```
class TestException extends \Exception { }

function test() {
  throw new TestException("bad");
}

try
{
  test();
}
catch (Exception $e)
{
  krumo($e); // Object with 4 elements
  krumo((array)$e); // Array with 7 elements, including Exceptiontrace 
}
```

**Comment by scottchiefbaker** [comment]
Good catch (no pun intended). I think this should be easy to work around if there is a way to test if a given object is an exception. I don't see an `is_exception()` function. I'll do some research on it, unless you already know a way to do this test.

**Comment by scottchiefbaker** [comment]
Ok I think I got it. What do you think of this demo: http://www.perturb.org/tmp/krumo-test.php

You can test the code by checking out my branch: https://github.com/scottchiefbaker/krumo/tree/exception_trace

**Comment by grippon** [comment]
Thanks.

I see Exceptionprevious is not forwarded as well, it may beuseful for some people (but i don't need it especially).

http://php.net/manual/en/exception.getprevious.php

**Comment by scottchiefbaker** [comment]
This is already merged, but never got closed.
