### ISSUE TITLE
Non-static method called statically

### ISSUE THREAD

**Issue by brendt** [mmucklo/krumo#34]
We're encountering these kind of issues more and more with the latest versions of Krumo.

```
Strict Standards:  Non-static method ride\web\base\controller\IndexController::indexAction() should not be called statically in /Users/User/Sites/Site/vendor/mmucklo/krumo/class.krumo.php on line 1215

Fatal error:  Using $this when not in object context in /Users/User/Sites/Site/vendor/ride/web-base/src/ride/web/base/controller/IndexController.php on line8
```

This is the snippet of our code which breaks Krumo:

``` php
<?php

namespace ride\web\base\controller;

class IndexController extends AbstractController {

    public function indexAction() {
        $this->setTemplateView('base/index');
    }

}
```

**Comment by scottchiefbaker** [comment]
This doesn't make sense to me. The code snippet you mention has nothing to do with Krumo. Where does Krumo fit in to this equation?

Somewhere (else) you're calling `IndexController::indexAction()` and you should be calling it as an object (not statically with the `class::method()` syntax. I don't think this error has anything to do with Krumo.

**Comment by mmucklo** [comment]
Let me take a look and see if I see anything...

**Comment by brendt** [comment]
@scottchiefbaker You're right, I forgot to mention, the error occurs when using Krumo in the smarty template which is rendered by this code snippet.

**Comment by scottchiefbaker** [comment]
You're using krumo INSIDE of a smarty template?

**Comment by brendt** [comment]
@scottchiefbaker Yes, while debuggen template variables

**Comment by mmucklo** [comment]
@brendt - did you every find a fix or work around for this?

**Comment by brendt** [comment]
@mmucklo Nope I did not; I guess my issue is a pretty specific use case, trying to use krumo in a Smarty template in a custom framework; so it's a pretty egde-case scenario.

I just stopped using krumo in those cases and used larapack/dd instead.

**Comment by mmucklo** [comment]
I did look into this a bit ago and found that it's probably related to this code:

```php
        // callback
        if (is_callable($data)) {
            $_ = array_values($data());
            print "<span class=\"krumo-callback\"> |";
            print " (<em class=\"krumo-type\">Callback</em>) <strong class=\"krumo-string\">";
```

I'm not sure why the index method itself is getting passed into the function yet, but that's the area the code is failing.  I'm not sure if there's a good work around or a way the error messaging could be clearer, though.

**Comment by scottchiefbaker** [comment]
I use Smarty as well... if you can tell me **how** you're calling Krumo inside of Smarty I can attempt to recreate it.

**Comment by brendt** [comment]
@scottchiefbaker I used it this way:

```
{kd($variable)}
```

**Comment by scottchiefbaker** [comment]
I'm calling krumo exactly like you describe above and I'm not getting an error. It's not exactly pretty inside of smarty, but I'm not getting an error. Can you recreate this with the latest version?

**Comment by brendt** [comment]
Hi, I'm actually not using Krumo anymore because of this issue. Now I'm not saying the issue is in Krumo's code, but it was a pain to work with it that way. So I have no up-to-date example no.

**Comment by scottchiefbaker** [comment]
Well I'm unable to recreate this, so I'm going to close this issue for now. You're welcome to re-open it later if it becomes and issue for you.

**Comment by mmucklo** [comment]
Scott, if $variable was a callable of some sort, in the format of an array callable I could see how it might have happened.  I'd have to think of a way to catch it, it it would make sense given the sort of error he encountered.
