### ISSUE TITLE
Don't truncate after 50 characters

### ISSUE THREAD

**Issue by prohtex** [mmucklo/krumo#39]
I've noticed that after 50 characters, a string is truncated, and then revealed in a subsequent div. Is there any option in the class to prevent this and output the entire string?

**Comment by scottchiefbaker** [comment]
Yes that's a configurable option in your `krumo.ini`. You may not have a `krumo.ini` (we use very sane defaults) so you may have to copy `krumo.sample.ini` to `krumo.ini` with the truncate option in place.

**Comment by prohtex** [comment]
Thanks! I was also wondering, does anyone have a javascript snippet for a quick and dirty "expand all"/"collapse all" button? Also, has anybody tried to save the expand/collapse states with cookies? Many thanks to those working on this project!

**Comment by scottchiefbaker** [comment]
If you double click on the footer it will expand/collapse all. (undocumented feature)

**Comment by scottchiefbaker** [comment]
Or you can call it:

`krumo($hash, KRUMO_EXPAND_ALL);`

to start it completely expanded.

**Comment by mmucklo** [comment]
closing as I believe the questions were answered...
