### ISSUE TITLE
Undefined index: class::

### ISSUE THREAD

**Issue by shovle** [mmucklo/krumo#40]
Hello,
Getting this error when calling dump:

`#0 Undefined index: class:: called at [.../www/vendor/mmucklo/krumo/class.krumo.php:532]`

It doesn't break anything, just letting you know Raygun throws this at me.

**Comment by scottchiefbaker** [comment]
How are you calling Krumo that you're getting this output?

**Comment by shovle** [comment]
I tried both the global function and the object based method: same error message.
I'm dumping get_defined_vars() for easy debugging some pages, but that shouldn't matter right?

**Comment by scottchiefbaker** [comment]
What were you trying to dump? Line 532 is a pretty weird line to die on. Line 532 is checking if you've disabled Krumo globally.

What version of PHP are you running?

**Comment by shovle** [comment]
Hey sorry for my late reply (had some time off).
We're running php 5.6.
I'm dumping `get_defined_vars()` not sure if that might be a problem?
Krumo doesn't die either, if we weren't running raygun I would have never noticed anything.
I just wanted to let you know that raygun keeps throwing these errors at me.

**Comment by shovle** [comment]
I'm guessing raygun ignores the @ error operator (didn't just found out about these).
I'll try with raygun, they should ignore these errors.

**Comment by mmucklo** [comment]
Let us know if there's anything else.

**Comment by kktsvetkov** [comment]
@scottchiefbaker + @mmucklo  Perhaps the code can be refactored not to have the silence operator at all? Right now it is
```php 
            if (in_array($function, array("krumo","k","kd")) || (strToLower(@$d['class']) == 'krumo') || (is_callable($callback) && call_user_func($callback, $d))) {
                break;
            }
```

Let's break it up into 3 separate statements with an extra check if the "class" element is not empty, like this:
```php
            if ( in_array($function, array("krumo", "k", "kd")) ) {
                break; // krumo alias function
            }
            if (!empty($d['class']) && ('krumo' == strToLower($d['class']))  ) {
                break; // krumo class method
            }
            if ( is_callable($callback) && call_user_func($callback, $d) ) {
                break; // callback
            }
```
It's more readable this way with each case for exiting the loop clearly defined, AND with the extra check that `$d['class']` is not empty.
