### ISSUE TITLE
Update Packagist?

### ISSUE THREAD

**Issue by sevn** [mmucklo/krumo#44]
Packagist isn't updating to the newest release even after a week. Can we please fix this up so I can >composer update to the newest version 💯 

Is it because there is no dev-master branch?

**Comment by scottchiefbaker** [comment]
I don't know who updates packagist. I've never done it. I assume someone in the community does that? Is there a way to see who submitted the package?

**Comment by sevn** [comment]
It finally updated..
I've never used packagist as a maintainer so I'm not 100% sure. The below text is from their website about the update schedule.

> New packages will be crawled immediately after submission if you have JS enabled.
> 
> Existing packages without auto-updating (GitHub/BitBucket hook) will be crawled once a week for updates. When a hook is enabled packages are crawled whenever you push, or at least once a month in case the crawl failed. You can also trigger a manual update on your package page if you are logged-in as a maintainer.
> 
> It is highly recommended to set up the GitHub/BitBucket service hook for all your packages. This reduces the load on our side, and ensures your package is updated almost instantly. Check the how-to below.
> 
> The search index is updated every five minutes. It will index (or reindex) any package that has been crawled since the last time the search indexer ran.

**Comment by scottchiefbaker** [comment]
We can look in to this for the next release.
