### ISSUE TITLE
How to change skin?

### ISSUE THREAD

**Issue by pdelisle6180** [mmucklo/krumo#45]
Command krumo::$skin = "default" doesn't work.
How does one change the skin?

**Comment by scottchiefbaker** [comment]
Skin selection should be done in the `krumo.ini` 

https://github.com/mmucklo/krumo/blob/master/krumo.sample.ini#L20

**Comment by pdelisle6180** [comment]
Getting error messages when using krumo.ini file.
[skin]
selected = "default"

GET http://localhost/krumo/skins/default/bg.gif 404 (Not Found)

I verified that the file bg.gif is in the directory!

No errors when using selected = "modern"

**Comment by scottchiefbaker** [comment]
I just tested with the `default` and `modern` skins and didn't see any errors. Are you seeing PHP errors, or browser console errors? If you navigate to that URL in your browser normally do you see something?

**Comment by pdelisle6180** [comment]
Errors show up in browser console (Chrome).
I am running this locally using Wamp on Windows.
In spite of the errors the krumo results do show up.

**Comment by pdelisle6180** [comment]
![krumo](https://user-images.githubusercontent.com/13306574/56511242-bbabb880-64f1-11e9-8d02-c4ac262412f2.jpg)

**Comment by pdelisle6180** [comment]
![krumo2](https://user-images.githubusercontent.com/13306574/56511402-19d89b80-64f2-11e9-85e0-5b42eb32c76d.jpg)

**Comment by scottchiefbaker** [comment]
If you navigate to that URL in your browser normally do you see something?

**Comment by pdelisle6180** [comment]
yes

**Comment by scottchiefbaker** [comment]
I'm not following. If you go directly to the URL it shows the image. Inside the context of a normal Krumo page that same URL doesn't load? I don't know how to help with that, as it sounds like something specific to your environment?

**Comment by pdelisle6180** [comment]
krumo for some reason is looking for the images (collapsed.gif and dotted.gif) in the wrong directory when using schablon.com in krumo.ini. I just uninstalled and reinstalled using composer and problem remains. It's looking for these images in the image directory instead of looking in vendor\mmucklo\krumo\skins\schablon.com

**Comment by scottchiefbaker** [comment]
I'm testing the `schablon.com` skin and it appears to be loading just fine. Can you post your `krumo.ini`, there might be a CSS config in there that's conflicting?

**Comment by scottchiefbaker** [comment]
Here is my [test case](https://www.perturb.org/tmp/test.php) using that skin.

I did a clone of this repo, and then copied the `krumo.sample.ini` to `krumo.ini` just to change the skin. Everything else is vanilla.

**Comment by pdelisle6180** [comment]
I'm using a copy of the provided sample krumo.ini and uncommented the line in the [skin] section.
Nothing else changed.

**Comment by scottchiefbaker** [comment]
That is so weird. I can't recreate what you're seeing. Maybe someone else will be able to?

**Comment by kktsvetkov** [comment]
@scottchiefbaker the images can be put inline inside the css files, so that there are no extra files to load, e.g.

`background: url(data:image/gif;base64,R0lGODlhWgAJALMAAP///8vLy+Tk5...zCnNapVdLBAA7);
	`

**Comment by scottchiefbaker** [comment]
Some of the skins already do that. I'd welcome patches to convert other skins to do the same.

**Comment by kktsvetkov** [comment]
@scottchiefbaker I've already converted my skins in 2017 in [ed1a544595e8](https://github.com/kktsvetkov/krumo/commit/ed1a544595e8a563c41b9367e3dad00271a2ad3c). Do you want a pull request or you can just copy the changes made to the css files from that commit?
