### ISSUE TITLE
Dropping VERSION file in favor of a class constant

### ISSUE THREAD

**Issue by kktsvetkov** [mmucklo/krumo#49]
Waaaay back at the beginning, many years ago, PHP libraries were distributed in a different way, with a different format. They were zipped and downloaded and everyone had to put them in their project. The VERSION file inside the package is a legacy remnant of that time. 

The current implementation is not optimal, because the VERSION file is read for every single dump Krumo makes:
```php
    public static function version()
    {
        return trim(file_get_contents(__DIR__ . "/VERSION"));
    }
...
            if ($showVersion) {
                $version = static::version();
                ...
            }
```

Let's just drop the VERSION file and move to a class constant, like this
```php
class Krumo
{
    const VERSION = '0.6.1';
    ...
```
And then reference that constant in all the places where the version needs to be printed. It will be way way faster and with a  smaller footprint since there will be no function calls, no trimming and no external file reading.

**Comment by scottchiefbaker** [comment]
Done.
