### ISSUE TITLE
Using a separate method for returning Krumo dumps instead using KRUMO_RETURN as argument

### ISSUE THREAD

**Issue by kktsvetkov** [mmucklo/krumo#50]
The krumo alias functions (`krumo()` and `k()`) that call krumo class methods are meant to be quick to type and use. I would argue that the extra `KRUMO_RETURN` makes it somewhat clumsy to type and use.

As an alternative, there can be a separate method that captures the output of `krumo::dump()` which requires no other arguments, like this
```php 
	/**
	* Return the dump information about a variable
	* @param mixed $data,...
	* @return string
	*/
	static function fetch($data)
	{
		// disabled ?
		//
		if (!self::_debug())
		{
			return false;
		}

		ob_start();
                call_user_func_array(
			array(self, 'dump'),
			func_get_args()
			);

                return ob_get_clean();
	}
```
It has a smaller footprint, and is faster to type because you type fewer characters and you do not have to switch cases to  uppercase:
```php
krumo($arr, KRUMO_RETURN);	// 26 chars, mixed case because of the uppercase constant
krumo::fetch($arr);		// 21 chars, all lowercase
```

You can also pass several arguments as once, like this:
```php
$html = krumo::fetch($first, $second, $third);
```
This will capture the output for all three arguments at once. This is another advantage over `KRUMO_RETURN`, because conventional `krumo::dump()` expects KRUMO_RETURN to be exactly the second argument. This again makes it clumsy to use variadic arguments when you want to return the dump instead of print it, like this:
```php
$html = krumo($first, KRUMO_RETURN) 
    . krumo($second, KRUMO_RETURN) 
    . krumo($third, KRUMO_RETURN);
```

**Comment by scottchiefbaker** [comment]
I like this feature.... well done.
