### ISSUE TITLE
Drop the INSTALL file

### ISSUE THREAD

**Issue by kktsvetkov** [mmucklo/krumo#52]
This is another legacy remnant (as VERSION in #49) from the early days of the project. The library now has README.md, where you can read how to install the library. The file itself is really old, it's from 7 years ago and it has not been updated to the latest changes: neither is anything about Composer inside it nor is a reference to krumo.sample.ini which replaced krumo.ini

It is pointless to maintain and update that file, so it is just best if it is dropped.

**Comment by scottchiefbaker** [comment]
Duh... all this info is in the README anyway. It's gone.
