### ISSUE TITLE
Put composer.lock in .gitignore and drop it

### ISSUE THREAD

**Issue by kktsvetkov** [mmucklo/krumo#53]
While it is a good practice to put your composer.lock in version control so that you can track the state of your project deployed dependencies, that's not the same for libraries such as Krumo.

You can read a very well detailed explanation here: https://stackoverflow.com/a/21589454

So let's put `composer.lock` in `.gitignore` and drop it

**Comment by scottchiefbaker** [comment]
I don't use composer, so I'm fine nuking this.

**Comment by kktsvetkov** [comment]
@scottchiefbaker it seems you did some of the changes in https://github.com/scottchiefbaker/krumo, but not in https://github.com/mmucklo/krumo repo. Perhaps you need to push them upstream?

**Comment by scottchiefbaker** [comment]
Good catch. I corrected this.
