### ISSUE TITLE
Drop "@static" and "@access public"

### ISSUE THREAD

**Issue by kktsvetkov** [mmucklo/krumo#55]
The Krumo project started as PHP4/PHP5 library. In PHP4 there is neither visibility scope nor explicit static methods. There were different ways to distinguish what is static, public, or non-public. The most obvious way was to use the phpdoc tags for `@access` and `@static`. These became moot with the complete PHP5 adoption and the retirement of PHP4. In PHP5 you explicitly declare what methods and properties are static, and what properties and methods are not public. That makes it meaningless to keep both `@static` and `@access public` -- static methods are explicitly declared as such, and the publicly accessible methods are obvious.

Let's drop these PHP4 legacy remnants.

**Comment by scottchiefbaker** [comment]
I've never once  used those comment blocks you reference. I assume they're for some PHPDOC stuff?

They're just inherited comments. I'll remove them.

**Comment by kktsvetkov** [comment]
Yes, they are phpdoc tags used when PHP4 was popular, and as I said now they are meaningless since PHP5 and ongoing you can explicitly set what is static or not public
