### ISSUE TITLE
Drop KRUMO_DIR, replace with __DIR__

### ISSUE THREAD

**Issue by kktsvetkov** [mmucklo/krumo#56]
That's a repeating theme with some other issues I posted today: the project carries a lot of legacy from its PHP4 origins.

The KRUMO_DIR constant is a tool to load the JS and CSS files when they are exposed in web-accessible folders. Now you can do all of that with __DIR__ which will allow you to find all the files and folders you need relevant to project root. 

There are 5 references to `KRUMO_DIR` in the code and they can all be replaced with `__DIR__`.

**Comment by scottchiefbaker** [comment]
Good call. This is an easy one. Thanks!
