### ISSUE TITLE
Change how configuration is operated

### ISSUE THREAD

**Issue by kktsvetkov** [mmucklo/krumo#58]
The INI-file configuration approach is really ancient. There are several problems with it:
* there is overhead in reading and parsing it 
* by default there is no configuration file, you have to set it up by copying `krumo.sample.ini` 
* if there is no configuration file loaded, there is no default configuration (although there are fallback values in `Krumo::_config()`

The whole INI file concept can be dropped. All the configurations can be operated from the class itself using `Krumo::setConfig()`, or something similar. Additionally, in most cases it is the same configuration that is being used across, and these settings are put as default values for the configuration, most people will just run with it without ever changing it. 

If not for anything else, it will make the installation of the library easier since there will be one less operation to deal with when you do not have to mingle with `krumo.sample.ini`

**Comment by scottchiefbaker** [comment]
I designed Krumo in such a way that 90% of users will **never** need a config file. If there is no `.ini` file found it will use defaults in the library itself. It has "sane" defaults, so only truly advanced users will need a config.

In other words, a config file is optional for my version.

**Comment by kktsvetkov** [comment]
I'll try to work on a pull request to show what changes I have in mind. I think mostly it will be about dropping the INI reading, plus some way to change the settings individually instead of using `Krumo::setConfig()`
