### ISSUE TITLE
Krumo doesn't cleanly support PHP 8.1

### ISSUE THREAD

**Issue by scottchiefbaker** [mmucklo/krumo#66]
There are a couple of minor tweaks required to make Krumo PHP 8.1 compliant. Fixes were landed in #64 and #65 which should address these issues. Please help the Krumo team test PHP 8.1 with the `next` branch and report any issues here. Pending a clean bill of health we will probably release Krumo 0.7.0 by the end of the week.

Thanks @driehle for bringing this to our attention.

**Comment by scottchiefbaker** [comment]
FWIW I've been testing this pending branch with PHP 8.0.21 and haven't experienced any issues. Not that I expected any, but I wanted to document it anyway :)

**Comment by driehle** [comment]
I have tested the `next` branch with one of my applications as well and now I am not receiving deprecation messages anymore. :)

**Comment by scottchiefbaker** [comment]
@driehle excellent... I'm gonna let it soak with my code for a couple days and if nothing crops up I'll release v0.7.0 on Friday-ish.

**Comment by scottchiefbaker** [comment]
This is an old issue and long since resolved.
