### ISSUE TITLE
Include handling of uninitialised objects in class

### ISSUE THREAD

**Issue by ggieling** [mmucklo/krumo#68]
I have a class that with some properties that are objects themselves (e.g. datetime objects, or mysqli objects). These objects are nor immediately initialised, they will only be initialised when needed.
When trying to use krumo on a object defined by a class that contains uninitialised objects as properties, an error message is generated and the script ends.

the error message is:

:  Uncaught Error: Typed property PatentCollection::$dbReader must not be accessed before initialization in .....
Stack trace:
#0 /srv/http/ipdev/includes_2018/krumo-master/class.krumo.php(1083): ReflectionProperty->getValue()
#1 /srv/http/ipdev/includes_2018/krumo-master/class.krumo.php(1285): Krumo::_vars()
#2 /srv/http/ipdev/includes_2018/krumo-master/class.krumo.php(888): Krumo::_object()
#3 /srv/http/ipdev/includes_2018/krumo-master/class.krumo.php(530): Krumo::_dump()
#4 /srv/http/ipdev/includes_2018/krumo-master/class.krumo.php(1640): Krumo::dump()

I guess that this may be solved by testing with [https://www.php.net/manual/en/reflectionproperty.isinitialized.php](https://www.php.net/manual/en/reflectionproperty.isinitialized.php)
If a property appears to be not initialised, skip processing it.

**Comment by scottchiefbaker** [comment]
Interesting. I'm not familiar with non-initialized objects. I will gladly work on some code to address this if you create a small testcase that recreates this issue.

**Comment by scottchiefbaker** [comment]
I'm probably due to get a new version of Krumo out to address some PHP 8.2 stuff anyway, so now is a decent time to look at it.

**Comment by ggieling** [comment]
The issue is actually with any non-initialised property.
In the below example:
```php
<?php

include_once ($_SERVER['DOCUMENT_ROOT'].'/includes_2018/krumo-master/class.krumo.php');

class dummy {

public string $teststring = 'test';
public array $fib = [1,2,3,5,8,13];
public ?string $emptystring;

}

$test = new dummy();
// $test->emptystring = null;
krumo($test);

echo 'krumo display succesfully completed';

?>

```
The above code generates an error message with the following content:
```
:  Uncaught Error: Typed property dummy::$emptystring must not be accessed before initialization in /srv/http/ipdev/includes_2018/krumo-master/class.krumo.php:1083
Stack trace:
#0 /srv/http/ipdev/includes_2018/krumo-master/class.krumo.php(1083): ReflectionProperty->getValue()
#1 /srv/http/ipdev/includes_2018/krumo-master/class.krumo.php(1285): Krumo::_vars()
#2 /srv/http/ipdev/includes_2018/krumo-master/class.krumo.php(888): Krumo::_object()
#3 /srv/http/ipdev/includes_2018/krumo-master/class.krumo.php(530): Krumo::_dump()
#4 /srv/http/ipdev/includes_2018/krumo-master/class.krumo.php(1640): Krumo::dump()
#5 /srv/http/ipdev/test/krumotest.php(15): krumo()
#6 {main}
  thrown in /srv/http/ipdev/includes_2018/krumo-master/class.krumo.php on line 1083
```
The error message is not visible in the browser, you have to go into the source code for the page to find it in the krumo structure.

After uncommenting the line:
```
// $test->emptystring = null;
```

The page succesfully displays the object structure and displays the success message below it.

Request in increasing level of desirability:
option 1)  make krumo skip uninitialised properties to prevent the situation that the krumo result is not visible. Krumo is mostly used in debugging, so it is desirable that it always produces a legible result.
option 2) make krumo not simply skip the uninitialised property, but include it with the remark that it is uninitialised.
option 3) make krumo include the uninitialised property with a warning below the krumo result that this property is uninitialised

**Comment by scottchiefbaker** [comment]
I'm circling back to this... I'd like to catch this error and handle it appropriately. I'm not super familar with uninitialized properties, so I'm not sure how I would test for one. The line that this is erroring on is:

```
$value = $property->getValue($data);
```

I don't see any PHP ways to test if a property is initialized or not. `isset()`, `empty()` and null coalesce don't work. I thought `property_exists()` might work, but no go there either. I can't try/catch it. 

How does one know if something is initialized or not?

**Comment by scottchiefbaker** [comment]
Scratch that... ChatGPT to the rescue. I just landed some code in 9639c9c that should do what you want, kind of. Right now we're just outputting it as `NULL`. Not sure if we want more details than that or not. Seems kind of corner-casey to me. Sticking with `NULL` might be enough short term.

Can you test and let me know?

**Comment by scottchiefbaker** [comment]
@ggieling I just landed some more specific code in `7cbf4df`. Check that version out and see if it does what you want.

**Note:** that version requires a minor CSS update for the krumo-not-init type so it displays in red.

![image](https://github.com/user-attachments/assets/283ac205-aa4d-44ea-ba0d-23c85e5054e0)

**Comment by scottchiefbaker** [comment]
This feature will go out in the next official version. I'll go do that now :)

**Comment by scottchiefbaker** [comment]
Version 0.7.2 is released and includes this fix
